import react from "@vitejs/plugin-react-swc";
import { defineConfig } from "vite";

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  define: {
    "process.env": process.env,
    "VITE_APP_TITLE": process.env.VITE_APP_TITLE,
    "VITE_APP_ICON": process.env.VITE_APP_ICON,
    "VITE_APP_BACKGROUND_COLOR": process.env.VITE_APP_BACKGROUND_COLOR,
    "VITE_APP_BUSINESS_CARD_PRIMARY_COLOR": process.env.VITE_APP_BUSINESS_CARD_PRIMARY_COLOR,
    "VITE_APP_BUSINESS_CARD_SECONDARY_COLOR": process.env.VITE_APP_BUSINESS_CARD_SECONDARY_COLOR,
    "VITE_APP_BUSINESS_CARD_TITLE": process.env.VITE_APP_BUSINESS_CARD_TITLE,
    "VITE_APP_BUSINESS_CARD_SUB_TITLE": process.env.VITE_APP_BUSINESS_CARD_SUB_TITLE,
    "VITE_APP_BUSINESS_CARD_INITIALS": process.env.VITE_APP_BUSINESS_CARD_INITIALS,
    "VITE_APP_BUSINESS_CARD_MOTTO": process.env.VITE_APP_BUSINESS_CARD_MOTTO,
    "VITE_APP_BUSINESS_CARD_VERSION": process.env.VITE_APP_BUSINESS_CARD_VERSION,
    "VITE_APP_BUSINESS_CARD_CONTACT_PHONE": process.env.VITE_APP_BUSINESS_CARD_CONTACT_PHONE,
    "VITE_APP_BUSINESS_CARD_CONTACT_GITHUB": process.env.VITE_APP_BUSINESS_CARD_CONTACT_GITHUB,
    "VITE_APP_BUSINESS_CARD_CONTACT_LINKEDIN": process.env.VITE_APP_BUSINESS_CARD_CONTACT_LINKEDIN,
    "VITE_APP_BUSINESS_CARD_CONTACT_EMAIL": process.env.VITE_VERCEL_ENV,
  },
});
